name: Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    node-version: [18.x]

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm
      - name: Run tests
        run: npm test
